services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/node_modules
    command: yarn dev
    environment:
      PORT: 5000
